CREATE TABLE instruments (
    id VARCHAR(64) PRIMARY KEY,
    isin VARCHAR(12) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    instrument_type VARCHAR(40) NOT NULL,
    coupon_percent NUMERIC(10,4) NOT NULL,
    maturity_date DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    sector VARCHAR(80) NOT NULL
);

CREATE TABLE market_data_ticks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id VARCHAR(64) NOT NULL,
    bid NUMERIC(18,6) NOT NULL,
    ask NUMERIC(18,6) NOT NULL,
    mid NUMERIC(18,6) NOT NULL,
    yield_percent NUMERIC(10,6) NOT NULL,
    spread_bps NUMERIC(10,4) NOT NULL,
    received_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_market_data_instrument_time ON market_data_ticks(instrument_id, received_at DESC);

INSERT INTO instruments (id, isin, name, issuer, instrument_type, coupon_percent, maturity_date, currency, sector)
VALUES
('bond-apple-2029', 'US037833AK68', 'Apple 2029 Senior', 'Apple Inc', 'CREDIT_BOND', 3.4500, DATE '2029-02-09', 'USD', 'Technology'),
('bond-bank-2031', 'US06051GJX30', 'Bank Senior 2031', 'Example Bank', 'CREDIT_BOND', 4.1250, DATE '2031-05-15', 'USD', 'Financials');

INSERT INTO market_data_ticks (instrument_id, bid, ask, mid, yield_percent, spread_bps, received_at)
VALUES
('bond-apple-2029', 98.120000, 98.180000, 98.150000, 5.210000, 95.0000, CURRENT_TIMESTAMP),
('bond-bank-2031', 96.300000, 96.420000, 96.360000, 5.870000, 145.0000, CURRENT_TIMESTAMP);
